# Firebase PROD
# @base_url = https://us-central1-doula-app-br.cloudfunctions.net/doula_app_backend_api_identity-prod
# Firebase QA
# @base_url = https://us-central1-kalea-cred.cloudfunctions.net/kalea_ecf_backend_api_client-qa
# Local
@base_url = http://localhost:6251

POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    //"username": "raphaelrdsoares@gmail.com",
    //"password": "Historico#Desgraca#737"
    	
    "username": "roberto.silva@kaleacred.com",
    "password": "beto@123"
    
    // "username": "laerte.rodrigues@kaleacred.com",
    // "password": "Caridade-Etereo-648"
}

###