# Firebase PROD
# @base_url = https://us-central1-doula-app-br.cloudfunctions.net/doula_app_backend_api_identity-prod
# Firebase QA
# @base_url = https://us-central1-doula-app-br.cloudfunctions.net/doula_app_backend_api_identity-qa
# Local
@base_url = http://localhost:6251

POST {{base_url}}/api/auth/login
Content-Type: application/json

{
    //"username": "raphael@gmail.com",
    //"password": "123456"
    "username": "laerte.rodrigues@kaleacred.com",
    "password": "Mutuamente.Uniformidade.895"
}

###